apiVersion: v1
kind: Secret
metadata:
  name: adirai-secrets
  namespace: adirai-connect
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongo:27017/adirai_connect_prod"
  JWT_ACCESS_SECRET: "replace_me"
  JWT_REFRESH_SECRET: "replace_me"

